const assert = require('node:assert/strict');
// Run against the local development server. Saves are read-only in this
// isolated browser; PLAYWRIGHT_MODULE can point to the bundled runtime module.
const { chromium } = require(process.env.PLAYWRIGHT_MODULE || 'playwright');
(async () => {
  const browser = await chromium.launch({ headless: true, channel: 'msedge' });
  const page = await browser.newPage({ viewport: { width: 1440, height: 900 } });
  const errors = [];
  page.on('pageerror', e => errors.push(e.message));
  await page.route('**/api/save-data**', r => r.request().method() === 'GET' ? r.continue() : r.fulfill({ status: 503, body: 'Read-only regression session' }));
  await page.route('**/api/native-gamepad', r => r.fulfill({ status: 200, json: { connected: false } }));
  await page.addInitScript(() => {
    window.pad = { id: 'Xbox standard', index: 0, connected: true, mapping: 'standard', axes: [0,0,0,0], buttons: Array.from({length:17}, () => ({pressed:false,value:0})), timestamp: 0 };
    Object.defineProperty(navigator, 'getGamepads', { value: () => [window.pad] });
  });
  const press = async n => {
    await page.evaluate(n => window.pad.buttons[n] = { pressed:true,value:1 }, n);
    await page.waitForTimeout(140);
    await page.evaluate(n => window.pad.buttons[n] = { pressed:false,value:0 }, n);
    await page.waitForTimeout(120);
  };
  const stick = async (axis, value, duration=120) => {
    await page.evaluate(([a,v]) => window.pad.axes[a] = v, [axis,value]);
    await page.waitForTimeout(duration);
  };
  const action = () => page.locator('.inventory-selected-actions [data-gamepad-selected="true"]').getAttribute('data-inventory-action');
  try {
    await page.goto(process.env.ECHOES_TEST_URL || 'http://127.0.0.1:3000');
    await page.waitForTimeout(18000);
    assert.deepEqual(errors, []);
    await page.locator('.inventory-trigger').click();
    const first = page.locator('.inventory-item').first();
    const box = await first.boundingBox();
    const name = await first.getAttribute('data-inventory-item-id');
    const quantity = await first.locator('small').innerText();
    await page.locator('.inventory-close').click();
    await page.mouse.move(box.x + box.width/2, box.y + box.height/2);
    await page.keyboard.press('Tab');
    await page.waitForTimeout(300);
    await stick(2, 0.6, 70); await stick(2, 0);
    await press(0); // first selects if needed
    if (!await page.locator('.inventory-selected-actions [data-gamepad-selected="true"]').count()) await press(0);
    assert.equal(await action(), 'use');
    assert.equal(await page.locator(`[data-inventory-item-id="${name}"] small`).innerText(), quantity);
    console.log('PASS virtual cursor item A enters actions without using item');
    await stick(0, 0.9, 100); await stick(0, 0);
    assert.equal(await action(), 'inspect');
    console.log('PASS left stick navigates action buttons');
    const inspectName = await page.locator('.inventory-selected-copy h3').innerText();
    const inspectDescription = await page.locator('.inventory-selected-copy > p').first().innerText();
    await press(0);
    assert.equal(await page.locator('.inventory-item-inspect-overlay').count(), 1);
    assert.equal(await page.locator('.inventory-item-inspect-name').innerText(), inspectName);
    assert.equal(await page.locator('.inventory-item-inspect-description').innerText(), inspectDescription);
    assert.equal(await page.locator('.inventory-item-inspect-exit [data-gamepad-glyph="B"]').count(), 1);
    assert.ok(await page.locator('.inventory-item-inspect-exit img').evaluate(e => e.getBoundingClientRect().height < 60));
    console.log('PASS inspect displays item data and the approved B glyph at hint size');
    await stick(2, -0.7, 200);
    await press(0);
    await page.waitForTimeout(350);
    assert.equal(await page.locator('.inventory-item-inspect-overlay').count(), 0);
    assert.equal(await action(), 'inspect');
    await page.waitForTimeout(400);
    assert.equal(await action(), 'inspect');
    console.log('PASS A closes inspect and restores selection even with right stick held');
    await stick(2,0);
    await press(0);
    assert.equal(await page.locator('.inventory-item-inspect-overlay').count(), 1);
    await stick(2,0.7,150);
    await press(1);
    await page.waitForTimeout(350);
    assert.equal(await action(),'inspect');
    console.log('PASS B uses the same inspect restoration');
    await stick(2,0);
    await press(0);
    await page.mouse.move(900,450);
    assert.equal(await page.locator('.inventory-inspect-mouse-icon').count(),1);
    assert.equal(await page.locator('.inventory-item-inspect-exit [data-gamepad-glyph]').count(),0);
    const touchSession = await page.context().newCDPSession(page);
    await touchSession.send('Emulation.setTouchEmulationEnabled',{enabled:true});
    await touchSession.send('Input.dispatchTouchEvent',{type:'touchStart',touchPoints:[{x:100,y:100}]});
    await page.waitForTimeout(100);
    assert.equal(await page.locator('.inventory-item-inspect-exit').innerText(),'輕觸畫面退出');
    await touchSession.send('Input.dispatchTouchEvent',{type:'touchCancel',touchPoints:[]});
    assert.equal(await page.locator('.inventory-item-inspect-overlay').count(),1);
    await touchSession.send('Emulation.setTouchEmulationEnabled',{enabled:false});
    await touchSession.detach();
    await page.setViewportSize({width:390,height:844});
    await page.waitForTimeout(250);
    const fits = await page.locator('.inventory-item-inspect-overlay').evaluate(root => {
      const title=root.querySelector('.inventory-item-inspect-name').getBoundingClientRect();
      const art=root.querySelector('.inventory-item-inspect-art').getBoundingClientRect();
      const footer=root.querySelector('.inventory-item-inspect-footer').getBoundingClientRect();
      return title.bottom <= art.top && art.bottom <= footer.top && footer.right <= innerWidth && footer.bottom <= innerHeight;
    });
    assert.equal(fits,true);
    await page.setViewportSize({width:1440,height:900});
    await page.waitForTimeout(250);
    await page.mouse.move(901,450);
    assert.equal(await page.locator('.inventory-inspect-mouse-icon').count(),1);
    console.log('PASS mouse/touch hints switch without stale glyphs; touch cancel and narrow layout work');
    await page.mouse.click(900,450);
    await page.waitForTimeout(350);
    assert.equal(await page.locator('.inventory-selected-actions [data-gamepad-selected="true"]').count(),0);
    assert.equal(await page.locator('.inventory-dialog').getAttribute('data-input-mode'),'keyboard-mouse');
    console.log('PASS real mouse closes inspect without restoring gamepad highlight');
    await page.locator('.inventory-item').nth(1).hover();
    await page.waitForTimeout(300);
    assert.equal(await page.locator('.inventory-item.is-selected').count(),1);
    await press(15);
    assert.equal(await page.locator('.inventory-item.is-selected').count(),1);
    console.log('PASS mouse and D-pad takeover keep exactly one item highlight');
    const second = page.locator('.inventory-item').nth(1);
    const secondId = await second.getAttribute('data-inventory-item-id');
    await second.hover();
    await press(0);
    assert.equal(await action(), 'use');
    assert.equal(await page.locator('.inventory-item.is-selected').getAttribute('data-inventory-item-id'), secondId);
    console.log('PASS mouse-to-A resumes the hovered item rather than the stale virtual cursor target');
    await stick(0,0.9,100);
    assert.equal(await action(),'inspect');
    await page.locator('.inventory-item').first().hover();
    await page.waitForTimeout(450);
    assert.equal(await page.locator('.inventory-dialog').getAttribute('data-input-mode'),'keyboard-mouse');
    assert.equal(await page.locator('.inventory-selected-actions [data-gamepad-selected="true"]').count(),0);
    await stick(0,0);
    console.log('PASS held left stick cannot reclaim input after a real mouse move');
    await press(0); await press(15); await press(0);
    assert.equal(await page.locator('.inventory-item-inspect-overlay').count(),1);
    await stick(2,0.7,100);
    await page.mouse.move(901,451);
    await page.waitForTimeout(300);
    await page.mouse.click(901,451);
    await page.waitForTimeout(350);
    assert.equal(await page.locator('.inventory-dialog').getAttribute('data-input-mode'),'keyboard-mouse');
    assert.equal(await page.locator('.inventory-selected-actions [data-gamepad-selected="true"]').count(),0);
    await stick(2,0);
    console.log('PASS held right stick cannot steal mouse ownership during inspect or its closing fade');
    assert.deepEqual(errors,[]);
    if (process.env.ECHOES_TEST_SCREENSHOT) await page.screenshot({path:process.env.ECHOES_TEST_SCREENSHOT});
  } finally { await browser.close(); }
})().catch(e => { console.error(e); process.exitCode=1; });
